apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana

  template:
    metadata:
      labels:
        app: grafana
        try: "0"

    spec:
      containers:
        - name: grafana

          # Do not change the image tag in the base directory.
          # These are patched by Kustomize in the kustomization.yaml files.
          # Use the Kustomization files in the  /apps/dev/* or /apps/test/* etc directories instead.

          image: grafana:4.0.2-management

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: grafana-configmap
            - secretRef:
                name: grafana-secret

          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
          
          volumeMounts:
          - mountPath: /etc/grafana/grafana.conf
            name: grafana-config
            readOnly: true

      restartPolicy: Always
      volumes:
      - name: grafana-config
        hostPath:
          path: /opt/sofi/grafana/grafana.conf
          type: File
