apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.60.6   # pin to a stable version
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    persistence:
      enabled: true
      size: 2Gi
    adminUser: admin
    adminPassword: admin
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Admin
      auth:
        disable_login_form: true
