apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  chart:
    spec:
      chart: grafana
      version: "7.3.11" # pick a stable chart version
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1h0m0s
  values:
    persistence:
      enabled: true
      size: 2Gi

    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: dev2.sofi-platform.dk
      path: /grafana
      pathType: Prefix
      # tls: true
      annotations:
        kubernetes.io/ingress.class: "traefik"

    service:
      type: ClusterIP
      port: 80

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki.sofi.svc.cluster.local:3100
            isDefault: true

