apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  chart:
    spec:
      chart: grafana
      version: "10.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1h0m0s
  values:
    persistence:
      enabled: true
      size: 2Gi
    
    
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        kubernetes.io/ingress.class: traefik
      path: /grafana
      hosts:
        - dev2.sofi-platform.dk
        
      tls:
        - hosts:
          - dev2.sofi-platform.dk
          secretName: dev2.sofi-platform.dk-tls

    service:
      type: ClusterIP
      port: 80
    
    grafana.ini:
      auth.generic_oauth:
        enabled: true
        name: Keycloak-OAuth
        allow_sign_up: true
        client_id: grafana
        client_secret: hpRnZ1rA85oyo3L1oxG1vohhvZLIrC20
        scopes:  openid email profile offline_access roles
        email_attribute_path:  email
        login_attribute_path:  username
        name_attribute_path:  full_name
        auth_url:  https://dev2.sofi-platform.dk/auth/realms/Sofi/protocol/openid-connect/auth
        token_url:  https://dev2.sofi-platform.dk/auth/realms/Sofi/protocol/openid-connect/token
        api_url:  https://dev2.sofi-platform.dk/auth/realms/Sofi/protocol/openid-connect/userinfo
        role_attribute_path:  contains(roles[*], 'logging-access')

      server:
        domain: dev2.sofi-platform.dk
        root_url: "%(protocol)s://%(domain)s/grafana"
        serve_from_sub_path: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki.sofi.svc.cluster.local:3100
            isDefault: true

