apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  chart:
    spec:
      chart: grafana
      version: "7.3.11" # pick a stable chart version
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1h0m0s
  values:
    persistence:
      enabled: true
      size: 2Gi

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        kubernetes.io/ingress.class: traefik
      path: /grafana/
      hosts:
         - dev2.sofi-platform.dk
        
      # tls:
      #     hosts:
      #       - dev2.sofi-platform.dk
      #     secretName: dev2.sofi-platform.dk-tls

    service:
      type: ClusterIP
      port: 80
    
    grafana.ini:
      server:
        domain: dev2.sofi-platform.dk
        root_url: https://dev2.sofi-platform.dk/grafana/
        serve_from_sub_path: true

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki.sofi.svc.cluster.local:3100
            isDefault: true

