apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: mqtt
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: management      
      port: 15672
      protocol: TCP
      targetPort: 15672
  selector:
    app: rabbitmq
  type: LoadBalancer
