apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  chart:
    spec:
      chart: grafana
      version: "9.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1h0m0s
  values:
    persistence:
      enabled: true
      size: 2Gi
    
    
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        kubernetes.io/ingress.class: traefik
      path: /grafana
      hosts:
        - sofi-platform.dk
        
      tls:
        - hosts:
            - sofi-platform.dk
          secretName: sofi-platform.dk-tls

    service:
      type: ClusterIP
      port: 80
    
    grafana.ini:
      auth.generic_oauth:
        tls_skip_verify_insecure: true
        enabled: true
        name: Keycloak-OAuth
        client_id: grafana
        scopes: openid email profile offline_access roles
        email_attribute_path: email
        login_attribute_path: username
        name_attribute_path: full_name
        auth_url: https://sofi-platform.dk/auth/realms/sofi/protocol/openid-connect/auth
        token_url: https://sofi-platform.dk/auth/realms/sofi/protocol/openid-connect/token
        api_url: https://sofi-platform.dk/auth/realms/sofi/protocol/openid-connect/userinfo
        role_attribute_path: "contains(realm_access.roles[*], 'logging-access') && 'Admin'"

      server:
        domain: sofi-platform.dk
        root_url: "%(protocol)s://%(domain)s/grafana"
        serve_from_sub_path: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki.sofi.svc.cluster.local:3100
            isDefault: true

