apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sofi
resources:
  - ../../base/sap-api/
  - configmap.yaml
  - ingress.yaml
images:
  - name: ghcr.io/ssi-dk/sap-api
    newName: ghcr.io/ssi-dk/sap-api
    newTag: "v2.27.15"
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: sap-api
    path: deployment-patch.yaml
