apiVersion: apps/v1
kind: Deployment
metadata:
  name: bifrost-queue-broker
spec:
  template:
    spec:
      containers:
        - name: bifrost-queue-broker
          image: ghcr.io/ssi-dk/bifrost-queue-broker-lims-request:v2.31.0
