apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sofi
resources:
  - ../../base/bifrost-queue-broker/
  - configmap.yaml
images:
  - name: ghcr.io/ssi-dk/bifrost-queue-broker
    newName: ghcr.io/ssi-dk/bifrost-queue-broker
    newTag: "v2.26.4"
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: bifrost-queue-broker
    path: deployment-patch.yaml
