apiVersion: apps/v1
kind: Deployment
metadata:
  name: bioapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bioapi

  template:
    metadata:
      labels:
        app: bioapi
        try: "0"

    spec:
      containers:
        - name: bioapi

          # Do not change the image tag in the base directory.
          # These are patched by Kustomize in the kustomization.yaml files.
          # Use the Kustomization files in the  /apps/dev/* or /apps/test/* etc directories instead.

          image: ghcr.io/ssi-dk/bio_api:1.0

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: bioapi-configmap
            - secretRef:
                name: bioapi-secret

          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
          - mountPath: /app/dmx_data
            name: dmx-data
            readOnly: false
          

      restartPolicy: Always
      volumes:
      - name: dmx-data
        # mount /data/foo, but only if that directory already exists
        hostPath:
          path: /opt/sofi/dmx-data # directory location on host
          type: Directory # this field is optional
