apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sofi
resources:
  - ../../base/sap-web/
  - configmap.yaml
  - ingress.yaml
images:
  - name: ghcr.io/ssi-dk/sap-web
    newName: ghcr.io/ssi-dk/sap-web
    newTag: "v2.13.0"
