apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sofi
resources:
  - ../../base/bifrost-listener/
  - configmap.yaml
images:
  - name: ghcr.io/ssi-dk/bifrost-listener
    newName: ghcr.io/ssi-dk/bifrost-listener
    newTag: "v2.13.0"
