apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  chart:
    spec:
      chart: alloy
      version: "1.2.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1h0m0s
  values:
    alloy:
      configMap:
        create: true
        name: alloy-config
        content: |-
          logging {
            level = "info"
            format = "logfmt"
          }
          loki.write "default" {
            endpoint {
              url = "http://loki.sofi.svc.cluster.local:3100/loki/api/v1/push"
            }
          }
          discovery.kubernetes "pod" {
            role = "pod"
            // Restrict to pods on the node to reduce cpu & memory usage
            selectors {
              role = "pod"
              field = "spec.nodeName=" + coalesce(sys.env("HOSTNAME"), constants.hostname)
            }
          }
          // loki.source.kubernetes tails logs from Kubernetes containers using the Kubernetes API.
          loki.source.kubernetes "pod_logs" {
            targets    = discovery.kubernetes.pod
            forward_to = [loki.write.default.receiver]
          }
          