apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  chart:
    spec:
      chart: alloy
      version: "1.2.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1h0m0s
  values:
    alloy:
      configMap:
        create: true
        name: alloy-config
        content: |-
          logging {
            level = "debug"
            format = "logfmt"
          }
          loki.write "default" {
            endpoint {
              url = "http://loki.sofi.svc.cluster.local:3100/loki/api/v1/push"
            }
          }

          discovery.kubernetes "pods" {
            role = "pod"
          }

          discovery.kubernetes "services" {
            role = "service"
          }

          loki.source.kubernetes "services" {
            targets    = discovery.kubernetes.services.targets
            forward_to = [loki.write.default.receiver]
          }



          loki.source.kubernetes "pods" {
            targets    = discovery.kubernetes.pods.targets
            forward_to = [loki.write.default.receiver]
          }
          