apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sofi
nameSuffix: -tbr-request
resources:
  - ../../base/bifrost-queue-broker/
  - configmap.yaml
images:
  - name: ghcr.io/ssi-dk/bifrost-queue-broker-tbr-request
    newName: ghcr.io/ssi-dk/bifrost-queue-broker-tbr-request
    newTag: "v2.30.3"
patches:
  - path: patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: bifrost-queue-broker
