apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sofi
resources:
  - ../../base/bifrost-queue-broker/
  - configmap.yaml
images:
  - name: ghcr.io/ssi-dk/bifrost-queue-broker-tbr-request
    newName: ghcr.io/ssi-dk/bifrost-queue-broker-tbr-request
    newTag: "v2.27.0"