apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sofi
nameSuffix: -lims-pull
resources:
  - ../../base/bifrost-queue-broker/
  - configmap.yaml
images:
  - name: ghcr.io/ssi-dk/bifrost-queue-broker-lims-pull
    newName: ghcr.io/ssi-dk/bifrost-queue-broker-lims-pull
    newTag: "v2.27.0"
patchesStrategicMerge:
  - patch.yaml
