apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: sofi
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 3.0.0   # pick an appropriate stable version
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    persistence:
      enabled: true
      size: 10Gi
    mode: monolithic    # or “microservices” if you need scale and HA