apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: 2.9.*   # pick stable version
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    grafana:
      enabled: false   # since you already deploy Grafana separately
    promtail:
      enabled: true    # to collect logs
    loki:
      persistence:
        enabled: true
        size: 10Gi
