apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: sofi
spec:
  chart:
    spec:
      chart: loki
      version: "5.38.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: sofi
  interval: 1h
  values:
    loki:
        auth_enabled: false
    auth_enabled: false
    auth:
      enabled: false
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
    # Zero out replica counts of other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
    grafana-agent-operator:
      enabled: false
    logs:
      enabled: false